### ISSUE TITLE
Setup script as Kubernetes Cronjob

### ISSUE THREAD

**Issue by davidgasquez** [bufferapp/customer-health-scores#1]

**Comment by davidgasquez** [comment]
The `CronJob` is now scheduled @jwinternheimer! I'll keep an eye on it for the next few days and check if everything works properly! 😃 

Keeping this issue opened until we're sure it works!

**Comment by davidgasquez** [comment]
The CronJob didn't execute properly during the weekend but after tweaking the deployment configuration is now working!

It'll be running every day at 16:00 UTC. 😉

**Comment by jwinternheimer** [comment]
Awesome, thanks David!
