### ISSUE TITLE
Memory required to run the job

### ISSUE THREAD

**Issue by davidgasquez** [bufferapp/customer-health-scores#6]
Hey there @jwinternheimer! Would love to chat about the requirements for this job.

I've been able to run the job locally but it kills my computer (16GB RAM :sweat_smile:). The same is happening in Kubernetes due the amount of RAM it requires. 

We could potentially upgrade our nodes to more powerful ones but I'd love to check with you if there is a way of reducing the memory usage of the script. 

Not sure if we can reduce the dataset or, ideally, train the model once and load it to predict. Curious what do you think about this! :smiley:

**Comment by jwinternheimer** [comment]
Hey @davidgasquez, thanks for the issue! I've been meaning to revisit this model. There are surely some optimizations we could make. 😄

**Comment by davidgasquez** [comment]
Would love to help anywhere! I would like to have it in Kubernetes as soon as possible so you can stop thinking about running it manually.
